import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/Navbar";
import { CartProvider } from "../context/CartContext";
import { AuthProvider } from "../context/AuthContext";
import { FavoritesProvider } from "../context/FavoriteContext";
import { Playfair_Display } from "next/font/google";
import Footer from "@/components/Footer";

export const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${playfair.className} bg-[#F5F3EF] text-stone-900`}
        suppressHydrationWarning
      >
        {/* App Shell */}
        <div className="min-h-screen flex flex-col overflow-x-hidden">
          <AuthProvider>
            <FavoritesProvider>
              <CartProvider>
                <Navbar />

                {/* Main content */}
                <main className="flex-1">
                  {children}
                </main>

                <Footer />
              </CartProvider>
            </FavoritesProvider>
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
